version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t imagename-Dockerfile .
      - echo "Tagging Docker image..."
      - docker tag imagename-Dockerfile:latest 446641444093.dkr.ecr.us-east-1.amazonaws.com/jetbrains11:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 446641444093.dkr.ecr.us-east-1.amazonaws.com/jetbrains11:latest
